export * from "./anime.addapter";
export * from "./chapter.addapter";
export * from "./user.addapter";
export * from "./paginate.addapter";
export * from "./user-anime.addapter";
export * from "./favorite.addapter";
export * from "./tag.addpater";
export * from "./notification.addapter";
export * from "./user-chapter-history.addapter";
