version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://root:example@database:27017
      - JWT_SECRET=${JWT_SECRET:-your_awesome_secret_key}
      - PORT=${PORT:-3000}
    ports:
      - ${PORT}:3000
    links:
      - database:database
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./.dev/mongodata:/data/db
